[package]
name = "tetris"
version = "0.1.0"
authors = ["sunreal <jacob.sun.meta@gmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.85.0"
find_folder = "0.3.0"
rand = "0.6.1"
piston2d-sprite = "0.47.0"
piston-ai_behavior = "0.26.0"
